# /// script
# dependencies = [
#   "matplotlib",
#   "pandas",
#   "scienceplots",
# ]
# ///

"""Benchmark plotting script for Matrix Multiplication algorithms.

This script parses benchmark CSV files generated by the Rust benchmark runner
and plots the performance (Effective GFLOPS vs Matrix Size) using matplotlib
and scienceplots. It supports plotting sequential and parallel execution modes,
generating grid plots for comparisons (e.g. between faer and dgemm bases), and
incorporating reference curves from literature (e.g. Ballard reference lines).
"""

import argparse
import os
import sys
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

import plot_utils


def plot_csv(csv_path: str, output_path: str, mode: str = "both") -> None:
    """Generates performance plots from a benchmark CSV file.

    Args:
        csv_path: Path to the input CSV file.
        output_path: Default fallback path to save the output plot.
        mode: The plotting mode ("sequential", "parallel", "both").
    """
    if not os.path.exists(csv_path):
        print(f"Error: CSV file not found at {csv_path}")
        return

    df = pd.read_csv(csv_path, skipinitialspace=True)

    # Extract baseline timings from the corresponding base CSV if it exists
    dir_name = os.path.dirname(csv_path)
    base_name = os.path.basename(csv_path)
    if "benchmark_results" in base_name:
        base_csv_name = base_name.replace("benchmark_results_levels", "benchmark_results_base") \
                                 .replace("benchmark_results_cutoff", "benchmark_results_base") \
                                 .replace("benchmark_results", "benchmark_results_base")
    else:
        base_csv_name = "base_" + base_name
    base_csv_path = os.path.join(dir_name, base_csv_name)

    df_base = pd.DataFrame(columns=["size", "mkl_seq", "mkl_par", "faer_seq", "faer_par"])
    if os.path.exists(base_csv_path):
        try:
            df_base = pd.read_csv(base_csv_path, skipinitialspace=True)
        except Exception as e:
            print(f"Warning: Failed to load baseline timings from {base_csv_path}: {e}")

    # Check if there are multiple recursion levels or cutoffs to avoid zigzag lines
    has_levels = "recursion_level" in df.columns and not df["recursion_level"].dropna().empty
    has_cutoffs = "size_cutoff" in df.columns and not df["size_cutoff"].dropna().empty

    if has_levels:
        unique_levels = sorted(df["recursion_level"].dropna().unique())
        if len(unique_levels) == 1:
            level = unique_levels[0]
            df_runs = df
            if not df_base.empty:
                df_runs = df_runs.drop(columns=["mkl_seq", "mkl_par", "faer_seq", "faer_par"], errors="ignore")
                df_runs = pd.merge(df_runs, df_base, on="size", how="left")
            plot_df_core(df_runs, output_path, mode=mode, recursion_level=level)
        else:
            for level in unique_levels:
                df_level = df[df["recursion_level"] == level]
                df_runs = df_level
                if not df_base.empty:
                    df_runs = df_runs.drop(columns=["mkl_seq", "mkl_par", "faer_seq", "faer_par"], errors="ignore")
                    df_runs = pd.merge(df_runs, df_base, on="size", how="left")
                
                base, ext = os.path.splitext(output_path)
                level_out_path = f"{base}_level_{int(level)}{ext}"
                print(f"Plotting level {int(level)} -> {level_out_path}")
                plot_df_core(df_runs, level_out_path, mode=mode, recursion_level=level)
                
    elif has_cutoffs:
        unique_cutoffs = sorted(df["size_cutoff"].dropna().unique())
        if len(unique_cutoffs) == 1:
            cutoff = unique_cutoffs[0]
            df_runs = df
            if not df_base.empty:
                df_runs = df_runs.drop(columns=["mkl_seq", "mkl_par", "faer_seq", "faer_par"], errors="ignore")
                df_runs = pd.merge(df_runs, df_base, on="size", how="left")
            plot_df_core(df_runs, output_path, mode=mode, size_cutoff=cutoff)
        else:
            for cutoff in unique_cutoffs:
                df_cutoff = df[df["size_cutoff"] == cutoff]
                df_runs = df_cutoff
                if not df_base.empty:
                    df_runs = df_runs.drop(columns=["mkl_seq", "mkl_par", "faer_seq", "faer_par"], errors="ignore")
                    df_runs = pd.merge(df_runs, df_base, on="size", how="left")
                    
                base, ext = os.path.splitext(output_path)
                cutoff_out_path = f"{base}_cutoff_{int(cutoff)}{ext}"
                print(f"Plotting cutoff {int(cutoff)} -> {cutoff_out_path}")
                plot_df_core(df_runs, cutoff_out_path, mode=mode, size_cutoff=cutoff)
    else:
        df_runs = df
        if not df_base.empty:
            df_runs = df_runs.drop(columns=["mkl_seq", "mkl_par", "faer_seq", "faer_par"], errors="ignore")
            df_runs = pd.merge(df_runs, df_base, on="size", how="left")
        plot_df_core(df_runs, output_path, mode=mode)


def plot_df_core(
    df: pd.DataFrame,
    output_path: str,
    mode: str = "both",
    recursion_level: float = None,
    size_cutoff: float = None,
) -> None:
    """Core logic to generate a performance plot from a dataframe in both PDF and PNG formats.

    Converts benchmark timings to Effective GFLOPS and normalizes parallel results.
    Overlays reference lines from the Ballard benchmark suite.

    Args:
        df: A pandas DataFrame containing benchmark timings.
        output_path: The target filepath to save the plot (.pdf).
        mode: The plotting mode to filter by ('sequential', 'parallel', or 'both').
        recursion_level: Optional recursive level fallback parameter.
        size_cutoff: Optional cutoff fallback size parameter.
    """
    plot_utils.setup_matplotlib_style()

    fig, ax = plt.subplots(figsize=(8, 5.5), dpi=300)
    num_cores = os.cpu_count() or 1

    for col in df.columns:
        if col in ["size", "only_base", "base_choice", "recursion_level", "size_cutoff"]:
            continue

        if df[col].isna().all():
            continue

        is_col_parallel = plot_utils.is_parallel(col)
        if mode == "sequential" and is_col_parallel:
            continue
        if mode == "parallel" and not is_col_parallel:
            continue

        style = plot_utils.ALGORITHM_STYLES.get(col, {"marker": "x", "linestyle": ":"})
        gflops = plot_utils.calculate_gflops_rust(df["size"], df[col], is_parallel=is_col_parallel, num_cores=num_cores)

        ax.plot(
            df["size"],
            gflops,
            label=plot_utils.format_label(col),
            linewidth=1.2,
            markersize=4.5,
            **style,
        )

    # Determine which Ballard modes to plot based on the active columns
    active_modes = set()
    for col in df.columns:
        if col in ["size", "only_base", "base_choice", "recursion_level", "size_cutoff"] or df[col].isna().all():
            continue

        is_col_parallel = plot_utils.is_parallel(col)
        if mode == "sequential" and is_col_parallel:
            continue
        if mode == "parallel" and not is_col_parallel:
            continue

        if is_col_parallel:
            active_modes.update(["dfs", "bfs", "hybrid"])
        else:
            active_modes.add("seq")

    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)

    for m in sorted(active_modes):
        data = plot_utils.load_ballard_data(project_root, m)
        if data:
            mode_labels = {"seq": "Seq", "dfs": "DFS", "bfs": "BFS", "hybrid": "Hybrid"}
            strassen_dfs = []
            if recursion_level is not None and not pd.isna(recursion_level):
                level = int(recursion_level)
                if 1 <= level <= len(data["strassen"]):
                    strassen_dfs.append((level, data["strassen"][level - 1]))

            plot_utils.plot_ballard_lines(
                ax,
                data["mkl"],
                strassen_dfs,
                mode_label=mode_labels.get(m, m.upper()),
                num_cores=num_cores if m != "seq" else 1,
            )

    ax.set_xscale("log", base=2)
    ax.set_yscale("linear")
    ax.set_xlabel(r"Matrix Size ($N \times N$)", labelpad=10)
    ax.set_ylabel(
        r"Effective GFLOPS / core" if mode == "parallel" else r"Effective GFLOPS",
        labelpad=10,
    )

    subtitle = ""
    if recursion_level is not None and not pd.isna(recursion_level):
        subtitle = f"Fallback to vendor matmul after {int(recursion_level)} recursive step"
    elif size_cutoff is not None and not pd.isna(size_cutoff):
        subtitle = f"Fallback to vendor matmul when N $\\le$ {int(size_cutoff)}"

    title = "Matrix Multiplication Performance Comparison"
    if subtitle:
        title += f"\n{subtitle}"
    ax.set_title(title, pad=15)

    ax.set_xticks(df["size"])
    ax.get_xaxis().set_major_formatter(plt.ScalarFormatter())
    ax.legend(loc="upper left", frameon=True, framealpha=0.9)

    plt.tight_layout()
    plot_utils.save_plot(fig, output_path)
    plt.close(fig)


def clean_plot_dir(plot_dir: str) -> None:
    """Remove generated plot files (PDF and PNG) from the plot directory.

    Args:
        plot_dir: Path to the directory containing plots to be cleaned.
    """
    if not os.path.exists(plot_dir):
        print(f"Plot directory does not exist: {plot_dir}")
        return

    print(f"Cleaning plot directory: {plot_dir}...")
    removed_count = 0
    for filename in os.listdir(plot_dir):
        if filename.endswith(".pdf") or filename.endswith(".png"):
            file_path = os.path.join(plot_dir, filename)
            try:
                if os.path.isfile(file_path):
                    os.remove(file_path)
                    removed_count += 1
            except Exception as e:
                print(f"Error removing {file_path}: {e}")
    print(f"Removed {removed_count} plot files.")


def main() -> None:
    """Main execution block to check arguments, clean plots, and plot results."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, ".."))

    parser = argparse.ArgumentParser(description="Plot matrix multiplication benchmarks.")
    parser.add_argument("csv_path", nargs="?", default=None, help="Path to the input CSV file.")
    parser.add_argument(
        "--mode",
        "-m",
        choices=["sequential", "parallel", "both"],
        default="both",
        help="Plotting mode: sequential, parallel, or both (default: both).",
    )
    parser.add_argument(
        "--clean",
        "-c",
        action="store_true",
        help="Clean the output plots directory before/instead of plotting.",
    )
    args = parser.parse_args()

    csv_path = args.csv_path
    csv_paths_to_plot = []
    if csv_path is None:
        csv_dir = os.path.join(project_root, "generated", "csv")
        job_id = os.environ.get("SLURM_JOB_ID") or os.environ.get("PBS_JOBID") or os.environ.get("RUN_ID")
        if job_id:
            levels_file = os.path.join(csv_dir, f"benchmark_results_levels_{job_id}.csv")
            cutoff_file = os.path.join(csv_dir, f"benchmark_results_cutoff_{job_id}.csv")
            std_file = os.path.join(csv_dir, f"benchmark_results_{job_id}.csv")
            if os.path.exists(levels_file):
                csv_paths_to_plot.append(levels_file)
            if os.path.exists(cutoff_file):
                csv_paths_to_plot.append(cutoff_file)
            if not csv_paths_to_plot and os.path.exists(std_file):
                csv_paths_to_plot.append(std_file)
        else:
            levels_file = os.path.join(csv_dir, "benchmark_results_levels.csv")
            cutoff_file = os.path.join(csv_dir, "benchmark_results_cutoff.csv")
            std_file = os.path.join(csv_dir, "benchmark_results.csv")
            if os.path.exists(levels_file):
                csv_paths_to_plot.append(levels_file)
            if os.path.exists(cutoff_file):
                csv_paths_to_plot.append(cutoff_file)
            if not csv_paths_to_plot and os.path.exists(std_file):
                csv_paths_to_plot.append(std_file)
                
        if not csv_paths_to_plot:
            csv_paths_to_plot = [std_file]
    else:
        csv_paths_to_plot = [os.path.abspath(csv_path)]

    for csv_path in csv_paths_to_plot:
        csv_dir = os.path.abspath(os.path.dirname(csv_path))
        if os.path.basename(csv_dir) == "csv" and os.path.basename(os.path.dirname(csv_dir)) == "generated":
            out_dir = os.path.join(os.path.dirname(csv_dir), "plots")
        else:
            out_dir = csv_dir

        if args.clean:
            clean_plot_dir(out_dir)

        if os.path.exists(csv_path):
            base_name = os.path.basename(csv_path)
            if "results" in base_name:
                out_name = base_name.replace("results", "plot").replace(".csv", ".pdf")
            else:
                out_name = os.path.splitext(base_name)[0] + ".pdf"

            if args.mode == "both":
                output_path = os.path.join(out_dir, out_name)
            else:
                base, ext = os.path.splitext(out_name)
                output_path = os.path.join(out_dir, f"{base}_{args.mode}{ext}")

            print(f"Plotting {csv_path} (mode={args.mode}) -> {output_path}...")
            plot_csv(csv_path, output_path, mode=args.mode)
        else:
            if not args.clean:
                print(f"Error: CSV file not found at {csv_path}")


if __name__ == "__main__":
    main()
